### ISSUE TITLE
GA Tracking ID Change

### ISSUE THREAD

**Issue by bertrandk** [rangle/augury.angular.io#46]
A few days ago, the massive PR #24 changed the GA tracking ID. This not only harmed continuity of data (4 days of bad data and counting...) but it also interfered with new experiments on the page.

Was this done on purpose or by accident?

/cc @mobinni @ericjim

**Comment by mobinni** [comment]
Hi @bertrandk.

This definitely happened by accident. The codebase was altered and based of off master, so I'm thinking the previous production build was based off a different branch than master, that did have the correct tracking id's in place (@ericjim ?).

If you supply me with the correct tracking ID's I'd be happy to change them..

**Comment by bertrandk** [comment]
Ah, no worries. Don't feel the need to rush a fix on the weekend. I just wanted to check in before reverting an intentional change.

 In any case, we probably want: UA-41067508-8. It's odd really, I actually don't know where that other UA-ID goes to or comes from.

**Comment by mobinni** [comment]
@bertrandk are you able to receive tracking data now?

**Comment by bertrandk** [comment]
It looks like we're all good. Thanks.
